---
title: "Yeong Wei, Lai"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

### Architect | Software Professional Services | OSS | MANO

Mobile: [+6018-660 1566](https://wa.me/186601566) \
E-mail: yeongwei2004@yahoo.com \
LinkedIn: https://www.linkedin.com/in/yeong-wei-116v/ \
GitHub: https://github.com/yeongwei

# Professional Details

Company Name|Team|Position|Start Date|End Date
-----------------------|-----------------------|-----------------------|----------|--------
[Persistent Systems Malaysia Sdn Bhd](https://star.talentcorp.com.my/employer/search/view/709) (PSL)|Software Services|Architect|2022|Present
[Persistent Systems Malaysia Sdn Bhd](https://star.talentcorp.com.my/employer/search/view/709) (PSL)|Software Services|Project Lead|2020|2022
[Persistent Systems Malaysia Sdn Bhd](https://star.talentcorp.com.my/employer/search/view/709) (PSL)|Software Services|Staff Software Engineer|2018|2020
[Persistent Systems Malaysia Sdn Bhd](https://star.talentcorp.com.my/employer/search/view/709) (PSL)|Development|Staff Software Engineer|March 2014|2018
[Persistent Systems Malaysia Sdn Bhd](https://star.talentcorp.com.my/employer/search/view/709) (PSL)|Development|Contractor Staff|June 2012|March 2014
[IBM Malaysia Sdn Bhd](https://www.ibm.com/ibm/my/en/)|Development|Contractor Staff|June 2010|June 2012

***

# Project Details

## Vodafone Kabel Deutschland

***2024 Q1***

Vodafone Kabel Deutschland (The Customer), a prominent operator in the cable business within Germany is heavily invested in Amazon Web Service Cloud offerings as part of the infrastructure for delivering media related services to end consumers

This was a collaboration with Business Partner, [TATA Consultancy Services](https://www.tcs.com/) which includes Consultants from Europe and APAC regions to conduct a Proof-of-Concept (POC) using [IBM Watson AIOps](https://www.ibm.com/watson/aiops-overview/) for Service Management Use Cases

#### Scope / Responsibility

1. Map Customer aspirations to Product / Solution Capabilities 
2. Work closely with on site Consultants to devise solution plans
3. Technical leadership to Engineers for POC system setup

#### Contribution Highlights

1. POC completed in time with expected Use cases presented to The Customer successfully

## [U Mobile Sdn Bhd](https://www.u.com.my/)

***2022 - Current***

[U Mobile Sdn Bhd (U Mobile)](https://www.u.com.my/) is a one of the large telecommunication service provider companies in Malaysia. U Mobile decided to embark on a digital transformation journey for network service operation towards a zero-touch-autonomous model. U Mobile had chosen [IBM Watson AIOps](https://www.ibm.com/watson/aiops-overview/) which includes [Telco Network Cloud Manager for Performance (TNC-P)](https://www.ibm.com/docs/en/tncm-p/1.4.2) as the solution for this transformation roadmap

E2E delivery including Hardware (Network Equipment, Compute, Storage, Firewall, Load-balancer), Virtualization Platforms, Service Assurance Software, Solution Customization, Operation and Maintenance Support Services

Key Components include Event Management, Performance Management, Topology Management and Trouble Ticketing System

#### Scope / Responsibility

1. Technical presales and sales engagements. Request-for-Proposal (RFP) Solution Compliance vetting. E2e Solution proposal drafting. Solution presentation. Technical engagement with customer
2. RFP Awarded mid Year 2022, assigned as Technical Architect for deployment, leading a team of 7 Services Engineers
3. Post Go-live Accelerated Support Services
4. Drive new Use Cases with Customer

#### Contribution Highlights

1. Go-live successfully


## [Verizon Communications](https://www.verizon.com/)

***2021***

[Verizon Communications (Verizon)](https://www.verizon.com/) is a tier-1 telecommunication service provider company in the United States of America. Verizon wanted to refresh the existing Service Assurance platform with [IBM Watson AIOps](https://www.ibm.com/watson/aiops-overview/) which includes [Telco Network Cloud Manager for Performance (TNC-P)](https://www.ibm.com/docs/en/tncm-p/1.4.2)


#### Scope / Responsibility
1. Offshore Services leading on TNC-P deployment strategy
2. Work closely with deployment engineers on various TNC-P deployment issues
3. Work closely with TNC-P product development teams on features required by customer
4. Attend regular calls with customer for closing issues
5. Lead customization solution discussion with customer

#### Contribution Highlights

1. Deployment was completed on time and Verizon could meet the planned cut of date for the existing Service Assurance Platform with minimal operation interruption

## [TIME dotCom Bhd](https://www.time.com.my/)

***2020***

[TIME dotCom Bhd](https://www.time.com.my/) (TIME) is a telecommunication service provider company in Malaysia that has strong presence in both global and domestic markets. Domestically, TIME is famous for the consumer and enterprise leased lines products. In this project, TIME required a fully automated, dynamic, end-to-end Network Function Virtualization (NFV) service lifecycle management and network orchestration (MANO) solution for the enterprise leased line products

#### Scope / Responsibility

1. As Integration Lead, leading a team of 4.
2. Conduct requirement gathering with customer.
3. Solution Design and implementation, e2e including closed loop integration with Service Assurance Platform

#### Contribution Highlights
1. Project delivered on time.
2. Project had been chosen as case study and press release [here](https://www.ibm.com/case-studies/time-dotcom/)

## [Industrial and Commercial Bank of China](http://www.icbc-ltd.com/icbcltd/en/)

***2019***

[Industrial and Commercial Bank of China](http://www.icbc-ltd.com/icbcltd/en/) (ICBC) is one of the top tier banks in China. ICBC has been using Tivoli Network Performance Management (TNPM) for network monitoring. ICBC has roadmap for improving network supervision, TNPM is required to monitor the network at a lower granularity 

#### Scope / Responsibility

1. Tivoli Network Performance Management (TNPM) services engagement.
2. Planning and solution design for TNPM to support multiple granularity workloadw (including 1-minute granularity for critical network elements)
3. Redeployed colletor topology for supporting 1-minute Performance metric collections

#### Contribution Highlights
1. Commited services tasks completed on time.

## [AIA Malaysia](https://www.aia.com.my/en/index.html)

***2019***

[AskSara](https://www.aia.com.my/en/about-aia/media-centre/press-releases/2017/aia-launches-first-insurance-chatbot-in-malaysia.html) Chatbot migration from existing managed service platform into IBM Clod Watson Assistant / Conversation platform.

#### Scope / Responsibility
1. Requirements and features gathering / scoping / mapping
2. Watson Assistant Conversation flow design
3. SIT and UAT support / mediation. Production rollout and closure

#### Contribution Highlights
1. Project delivery completed on time for production rollout as planned.

## [Public Bank Bhd](https://www.pbebank.com/)

***2018***

Software services engagement for upgrade / integration between ISAM, TDI, SDS and custom Java web application for Access Management.

#### Scope / Responsibility
1. Integration and configuration activities
2. Update / fix broken integration points

#### Contribution Highlights
1. Project delivery completed on time for production rollout as planned.

## [Network Performance Insight](https://www.ibm.com/support/knowledgecenter/en/SSCVHB_1.2.2/product_overview/cnpi_preface_comp_suite1.html) (NPI)

***2016 - 2018***

A next generation network performance management software that integrates with the [IBM Netcool Operations Insight](http://www-03.ibm.com/software/products/en/netcool-operations-insight) (NOI) as an Enterprise Network Operation Support System (OSS) solution.

#### Scope / Responsibility
1. Product development
2. Automated End-to-end Built Verification Test (BVT) deployment and maintenance
3. Deployment / Services partner support

#### Contribution Highlights
1. **Product Features Developed / Implemented**
    + Kafka Schema Registry
    + Storage Optimizer Enhancement
        * Improved storage file pruning policy to fire based on file committed timestamp for delayed optimization use case.
        * Isolated `Scan` and `Delete` optimization path as user configurable parameter.
    + SBT Build Code Enhancement
        * Used [`ClasspathJarPlugin`](http://sbt-native-packager.readthedocs.io/en/latest/recipes/longclasspath.html#generate-a-classpath-jar) to resolve Java classpaths ordering and long classpaths issues.
    + JDBC Driver Implementation
        * Based on Apache Calcite and Avatica. Click [here](#apache-calcite-avatica) for more information.
        * Implementation to comply with [SQL-92 Gramma](https://en.wikipedia.org/wiki/SQL-92) and [Oracle Java JDBC Specification](http://download.oracle.com/otndocs/jcp/jdbc-4_1-mrel-spec/index.html).
    + [Multi Node / JVM](http://doc.akka.io/docs/akka/snapshot/dev/multi-node-testing.html) Test Specification for Clustering Feature
        * Implemented test code for launching cluster test scenario to reduce physical hardware dependency
    + Storage Writer
        * Implemented `RAW` and `Aggregation` data writers based on [Akka Actor](http://akka.io/) to support distributed computing capabilities with the actor-based concurrency design.

2. **Automated BVT Ecosystem**
    + Background, Jenkins to launch product components as Docker Containers, including installation and configurations; Feed data via data injection tool developed in-house; Execute End-to-End test implemented with [Scala Test](http://www.scalatest.org/) framework; Consolidate results as J-Unit reports; Followed by tear down / clean up.
    + Improved development and operation (DevOps) cycles.
        * Improved product build quality with bugs captured before build was released to Quality Assurance (QA) team.
        * Automated ecosystem reduces cost for executing BVT activities.

***

### Umbrella Performance Management

***2015 - 2016***

A Telecom industry project based in Dubai, code named "Umbrella Performance Management". Contributed as offshore professional service engineer.

#### Scope / Responsibility
1. Migrated Wireless Alarms from Staging to Production environment.
2. Implemented automated replication of Planned Outage (POHC) data with data enrichment.
3. Implemented tooling to generate Alarm Definitons for Cognos Cross-launch report facilities.

#### Contribution Highlights
1. Wireless Alarm migration - productizable candidate.
2. Automated Alarm Definition generation, reduced manual intervention and improved efficient.

***

### TNPM Wireline Technical Pre-Sale

***2015 - 2016***

New business opportunities around South-East Asia region with [Globe Telecom](https://www.globe.com.ph/) (Philippines) and [TrueMove](http://truemoveh.truecorp.co.th/?ln=en) (Thailand).

#### Scope / Responsibility
1. Prepared TNPM POC system according to Request For Proposal (RFP) use cases.
2. Demo-ed / Presented / Walked-through with potential user groups.
3. Collaborated with on-site teams to execute product integration (e.g. Fault Management, Dashboard User Interface) and data stitching (e.g. Inventory enrichment).

#### Contribution Highlights
1. Implemented custom configurations and topologies to process performance data from live devices including enterprise level groupings creation for data aggregation, custom report navigation and personalized Cognos Reports.
2. Integrated [TNPM DataView](https://www.ibm.com/support/knowledgecenter/SSBNJ7_1.3.2/com.ibm.tnpm.doc/DataView/ctnpm_dv_userguide.html) into a common [IBM Dashboard Application Service Hub instance](https://www.ibm.com/developerworks/community/groups/service/html/communitystart?communityUuid=b8caedd7-3aca-41c1-a9c1-7be87a51c50e) as part of unified user interface use case.
3. Integrated [TNPM DataChannel](http://www.ibm.com/support/knowledgecenter/SSBNJ7_1.4.1/install/ctnpm_installguide_tivolinetcoolperformancemanagerarchitecture-03-02.html) with [IBM Tivoli Netcool/OMNIbus](http://www-03.ibm.com/software/products/en/ibmtivolinetcoolomnibus) for SNMP Trap processing as part of fault management use case.
4. Integrated TNPM with [IBM Operation Analytics - Predictive Insights](http://www-03.ibm.com/software/products/en/ibm-operations-analytics---predictive-insights) via [Mass Data Extraction](https://www.ibm.com/support/knowledgecenter/SSBNJ7_1.3.2/com.ibm.tnpm.doc/pdf/pdf_tnpm_mass_data_extraction.pdf) for fault prediction use case.

***

### [TNPM Data Provider](https://www-304.ibm.com/software/brandcatalog/ismlibrary/details?catalog.label=1TW10NP6I)

***2015***

[TNPM](https://www.ibm.com/support/knowledgecenter/SSBNJ7_1.4.0/com.ibm.tnpm_1.4_kc.doc/quick_start/tnpm_1.4_quick_start_guide.html) product includes both Wireline and Wireless domains. Each delivers data as separated source. The TNPM Data Provider is a common RESTful API to access a common data federated layer.

#### Scope / Responsibility
1. Produced design and scope of features.
2. Implemented POC and conducted requirement screening for useful business use case.
3. Developed features that fits into the TNPM solution ecosystem.

#### Contribution Highlights
1. Eventual solution is a common RESTful interface that is installed into IBM WebSphere Application Server (WAS) via automated installer and consumes data from both Wireline and Wireless domains based on JDBC semantics and expose the unified data in JSON format.
2. Implemented single point installer that orchestrates installation and configuration into WAS to reduce installation and uninstallation overheads.

***

### [TNPM Alcatel-Lucent (ALU) 5620 SAMLogToFile](http://www.ibm.com/support/knowledgecenter/SSBNJ7_1.3.2/com.ibm.tnpm_tp13J.doc/pack_rel_notes/ctnpm_relnotes_alcatel-lucent5620sam_logtofile2.1.0.0_tech_pak.html)

***2012 - 2014***

ALU SAM is an enterprise end-to-end, multi-domain network and service management software. The former TNPM solution process both the `Performance` (e.g. CPU, MEM) and `Accounting` (e.g. Bandwidth, Utilization) data based on the `FindToFile` method. ALU advocates moving forward for OSS clients to use the `LogToFile` method for greater scalability. IBM InfoSphere DataStage (DataStage) as an interface to SAM for multiple data streams followed by network data processing and modelling with TNPM.

#### Scope / Responsibility
1. Re-designed and re-implemented the [TNPM UBA Bulk Collectors](http://www.ibm.com/support/knowledgecenter/SSBNJ7_1.4.1/bulk_collector/c_tnpm_bcol_intro_tnpmcollectortypes.html) to adapt new data schemas.
2. Ensured successful end-to-end solution integration.
3. Supported deployment activities and defects raised.

#### Contribution Highlights
1. With multiple data streams from DataStage and multiple collector topology from TNPM, this increased processing throughput to satisfies customer requirements on network growth.
2. Participated in ALU and PSL joint venture OSS certification activity in ALU facility (Ottawa, Canada), achieved 80% passing rate
3. Successful production rollout for [Telus](http://www.telus.com) (Canada).

***

### TNPM Cognos All-KPI Report Automation

***2010 - 2012***

TNPM Cognos deliverables include the All-KPI Report for data availability validation purposes. However it was costly to produce. An automation tool written to improve cost efficiency.

#### Scope / Responsibility
1. Proposed and designed automation ecosystem based on MVC framework.
2. Developed automation tool.

#### Contribution Highlights
1. Reduced development cost by approximately 60% (e.g. 5 days effort reduced to 2 days).

***

### TNPM [Technology Pack](http://www.ibm.com/support/knowledgecenter/SSBNJ7_1.4.0/com.ibm.tnpm_tp14D.doc/pack_install_config/ctnpm_tpinstall_introduction_modify_1.html) Solution

***2010 - 2012***

TNPM is capable of processing data collected from network elements with various protocols. Technology Packs provide the discovery, collection model and report definitions according to vendor (e.g. Huawei, Cisco, Ericsson and etc) device specifications.

#### Scope / Responsibility
1. Developed Technology Packs based for either SNMP or Universal Bulk Adapter (UBA) protocol.
2. Development task included,
    * Configured simulators. Either via [Mimic Simulator](http://www.gambitcomm.com/site/products/mimic_simulator.shtml) or file generator based on Perl.
    * Network discovery (e.g. Network Inventory) and collection (e.g. Network metrics) formulas creation based on either MIBs or Element Management System (EMS) specifications.
    * Network modelling tasks including metric data aggregation grouping rules, report navigational groups and collection strategy groupings.
    * Report creation for DataView and/or Cognos reporting.
    * Technology pack build process execution.
    * BVT execution before handing over to QA team.

#### Contribution Highlights
1. Produced various General Availability (GA) variant Technology Packs.

***

# Product / Software / Technology Experiences
Tivoli Netcool Performance Manager (TNPM) for Wireline (PROVISO), 
IBM Cognos Software Suite, IBM WebSphere Application Server,
IBM InfoSphere DataStage, 
IBM Common User Restful Interface (CURI), 
IBM Dashboard Application Service Hub (DASH), 
Apache Tomcat, 
Apache Web Server, 
Jetty Web Server, 
Alcatel-Lucent 5620 Service Aware Manager, 
Jenkins Integration Suite, 
Git Source Control, 
Oracle Relational Database, 
MySQL, 
PostgreSQL, 
H2, 
IBM DB2, 
Akka, 
Kafka, 
Zookeeper, 
Hadoop, 
Ambari,
IBM Open Platform (IOP),
Simple Build Tool (SBT), 
Apache ANT, 
Docker, 
KairosDB,
Kudu,
Cassandra,
IBM Security Access Manager (ISAM),
IBM Tivoli Directory Integrator (TDI),
IBM Security Directory Server (SDS/LDAP),
IBM Cloud Watson Assistant / Conversation,
IBM Agile Lifecycle Manager,
IBM Cloud Platform,
Kurbenetes,
Podman,
Red Hat OpenStack Platform,
Red Hat Ceph Storage,
Red Hat OpenShift Container Platform,
NodeJS,
Ansible,
Simple Network Management Protocol (SNMP),
Flow / Cisco Netflow, Sampled Flow,
IBM Tivoli/Netcool OMNIbus,
IBM Tivoli/Netcool Impact,
IBM Agile Service Manager

***

# Programming Skillsets
Java, Scala, PHP, Perl, JavaScripts, HTML, CSS, Bash Shell Scripting, SQL, R Programming, Python

***

# Education Details
Institute Name|Programme|Qualification|Completion Date
--------------|-----------------------|-----------------------|-----------------------
Coursera|[Android App Development Specialization by University of Vanderbilt](https://www.coursera.org/specializations/android-app-development)|Click [here](https://www.coursera.org/account/accomplishments/specialization/HRXPTKKGTLRV) for Course Certificate|June 2018
Coursera|[Data Science Specialization by Johns Hopkins University](https://www.coursera.org/specializations/jhu-data-science)|Click [here](hhttps://www.coursera.org/account/accomplishments/specialization/UE58SKEPR4N2) for Course Certificate|April 2016
Coursera|[Functional Programming Principles in Scala](https://www.coursera.org/learn/progfun1)|Click [here](https://www.coursera.org/account/accomplishments/records/rPPWH9QVjAudgQcA) for Course Certificate|June 2014
Tunku Abdul Rahman College|Electronic Engineering|Advanced Diploma|Jan 2010

***

# Open Source Software Contributions

## Apache [Calcite](https://calcite.apache.org/) & [Avatica](https://calcite.apache.org/avatica/)

Data management framework based on Java.

### JIRA References

ID                  |Description
--------------------|---------------------------------------------------------------------------------------------------------
[CALCITE-705](https://issues.apache.org/jira/browse/CALCITE-705)|DML in Avatica, and split Execute out from Fetch request
[CALCITE-666](https://issues.apache.org/jira/browse/CALCITE-666)|Anti-semi-joins against JDBC adapter give wrong results
[CALCITE-259](https://issues.apache.org/jira/browse/CALCITE-259)|Using sub-queries in CASE statement against JDBC tables generates invalid Oracle SQL
[CALCITE-646](https://issues.apache.org/jira/browse/CALCITE-646)|AvaticaStatement.execute method broken over remote JDBC




